#!/usr/bin/env bash
# This script configures Nginx to listen on port 80.

# Remove the default Nginx configuration file from /etc/nginx/sites-enabled
rm /etc/nginx/sites-enabled/default

# Create a symbolic link from /etc/nginx/sites-available/default to /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
service nginx restart
