#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

# Function to handle SIGQUIT and SIGTERM signals
function terminator() {
  rm /var/run/myscript.pid
  exit
}

# Trap the SIGQUIT and SIGTERM signals to call the terminator function
trap terminator SIGQUIT SIGTERM

# Create the file /var/run/myscript.pid containing its PID
echo "$$" > /var/run/myscript.pid

# Trap the SIGINT signal to display "Y U no love me?!"
trap 'echo "Y U no love me?!"' SIGINT

# Trap the SIGTERM signal to display "I hate the kill command"
trap 'echo "I hate the kill command" && terminator' SIGTERM

# Display "To infinity and beyond" indefinitely
while true
do
  echo "To infinity and beyond"
  sleep 2
done
