#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely,
# with a sleep 2 in between each iteration.
# Displays "I am invincible!!!" in between each iteration.

# Function to display "I am invincible" when receiving a SIGTERM signal
function display_invincible() {
  echo "I am invincible!!!"
}

# Trap the SIGTERM signal to call the display_invincible function
trap display_invincible SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
