#!/usr/bin/env bash
# run apache on holbertonschool/265-0 container

# Redirect ServerName to the Apache configuration file
echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Start the Apache service
service apache2 start
