#!/usr/bin/env bash
# This script runs the 'whoami' command as the specified user.

# Check if an argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Store the username passed as an argument in a variable
user="$1"

# Run 'whoami' command as the specified user
sudo -u "$user" whoami
